name: Sync Image to Docker Hub  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git pull
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: mark88015
          password: xuezi1004
          logout: false

      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          skopeo copy docker://docker.io/library/mysql:5.7 docker://registry.cn-hangzhou.aliyuncs.com/mark88015/mysql:5.7
          skopeo copy docker://docker.io/library/redis docker://registry.cn-hangzhou.aliyuncs.com/mark88015/redis:latest
          skopeo copy docker://docker.io/library/openjdk:8-jre docker://registry.cn-hangzhou.aliyuncs.com/mark88015/openjdk:8-jre
        # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
